### ISSUE TITLE
Social icons

### ISSUE THREAD

**Issue by rohandebsarkar** [rohandebsarkar/academic-folio#22]
I will be adding social icons later. This issue is to collect which social icons we should include now.
Comment with the social icons you would like to see.

**Comment by rohandebsarkar** [comment]
email, GitHub, LinkedIn, Mastodon

**Comment by pourmand1376** [comment]
For now, adding `font-awesome` package was a wise decision.

**Comment by rohandebsarkar** [comment]
Hey @pourmand1376, would like your feedback in one thing.

In order to make the header less cluttered on the home page we can do some thing like this:
![Screenshot 2023-02-12 at 21-40-32 Academic Folio](https://user-images.githubusercontent.com/50144004/218322681-93336a08-5fcb-47b6-b80a-45c418f9e176.png)

Removing the social icons from the header and putting them below the picture for better visibility.

Let me know what you feel about this change.

**Comment by pourmand1376** [comment]
Excellent. I love this idea.
