### ISSUE TITLE
Add Navbar like papermod (Remove Hamburger menu)

### ISSUE THREAD

**Issue by pourmand1376** [rohandebsarkar/academic-folio#54]
Take a look at [this theme](https://adityatelange.github.io/hugo-PaperMod/). I like the overall look and feel and I think I will add a color-theme similar to this. 

I always hated hamburger menus on mobile. They are not good for accessibility. This `Hugo-papermod` theme has done a good approach and I like it. 

I think we can let the users have the option to choose if they want to have this hamburger menu or not.

**Comment by rohandebsarkar** [comment]
We can definitely have an option for the users to choose from.
