### ISSUE TITLE
Blog page returns 404

### ISSUE THREAD

**Issue by pourmand1376** [rohandebsarkar/academic-folio#8]
This is what we see when go to `/blog` URL .

![image](https://user-images.githubusercontent.com/32064808/213919733-699f1758-0d30-403a-bf5b-d1bff73c75b6.png)

It shouldn't be the case. It should behave like [here](https://www.youtube.com/watch?v=8b2YTSMdMps&list=PLLAZ4kZ9dFpOnyRlyS-liKL5ReHDcj4G3&index=12)

**Comment by rohandebsarkar** [comment]
I think this is because the `layouts/_default/list.html` is empty.

**Comment by pourmand1376** [comment]
Very true. I populated that with random data and it is now ok.
