### ISSUE TITLE
Enhacement: Toggle Dark / Light mode

### ISSUE THREAD

**Issue by pourmand1376** [rohandebsarkar/academic-folio#9]
Is there any reason for not having an icon for dark/light mode?

**Comment by rohandebsarkar** [comment]
I am yet to figure out how to include icons as svg. I personally don't want to add the complete fontawesome library, since it will increase the resource size a lot.

I have seen a couple of dependencies that can be add to achieve svg icons. I will try them out later.

**Comment by pourmand1376** [comment]
Thanks. That's great.
